Add clarity to docs surrounding command line arguments, suggest data-dir when syncing, and polishing up for mainnet
status-im/nim-beacon-chain pull request #2527
Opened 2021-04-29 15:42 UTC by TennisBowling

it's all docs. I added a mainnet reference on the systemd page, added clarity to how command line arguments are given, suggested if they want to specify a data-dir on the syncing page (and also reminded them that they need to pass it to every command)

2021-05-03 11:52 UTC, 0xmiel requested changes

2021-05-03 11:52 UTC, 0xmiel commented on docs/the_nimbus_book/src/beacon-node-systemd.md
> +> Want to run on mainnet? just replace all instances of `prymont` to `mainnet`.
```suggestion
> If you want to run on mainnet, simply replace all instances of `prymont` with `mainnet`.
```

2021-05-03 11:52 UTC, 0xmiel commented on docs/the_nimbus_book/src/start-syncing.md
> +> If you want to put the database somewhere else, (e.g. an external ssd) pass the `--data-dir=/your/path`. ⚠️ If you are doing this, remember to pass this flag to **all** your nimbus calls.
```suggestion
> If you want to put the database somewhere else, (e.g. an external ssd) pass the `--data-dir=/your/path`. ⚠️ If you do this, remember to pass this flag to **all** your nimbus calls.
```

2021-05-03 11:52 UTC, 0xmiel commented on docs/the_nimbus_book/src/troubleshooting.md
> +When starting nimbus and you get,
```suggestion
If, on start,  you see
```

2021-05-03 11:52 UTC, 0xmiel commented on docs/the_nimbus_book/src/troubleshooting.md
> +Make sure that your command line flags are in the format of `--foo=bar`, `--baz`, or `--foo-bar=qux`.
```suggestion
Double check to see if your command line flags are in the correct format, i.e. `--foo=bar`, `--baz`, or `--foo-bar=qux`.
```

2021-05-04 11:05 UTC, arnetheduck commented on docs/the_nimbus_book/src/beacon-node-systemd.md
> +> If you want to run on mainnet, simply replace all instances of `prymont` with `mainnet`.
```suggestion
> If you want to run on mainnet, simply replace all instances of `pyrmont` with `mainnet`.
```

2021-05-04 21:04 UTC, TennisBowling commented
Review last commit and then ready for merge.

2021-05-05 06:52 UTC, arnetheduck commented on docs/the_nimbus_book/src/beacon-node-systemd.md
> +Create a `systemd` service unit file -- `nimbus-eth2-pyrmont.service` -- and save it in `/lib/systemd/system/`.
https://unix.stackexchange.com/a/367237 - `/etc/` is supposedly the correct path, not sure why `/lib` enters the picture?

2021-05-12 21:11 UTC, TennisBowling commented on docs/the_nimbus_book/src/beacon-node-systemd.md
> +Create a `systemd` service unit file -- `nimbus-eth2-pyrmont.service` -- and save it in `/lib/systemd/system/`.
here's the thing. `/etc/` is normally the correct path, yes. but if you want to be able to enable it on startup it makes a systemlink to `/etc/`, and so if you put it in /etc/, it won't be able to enable it on startup.
I had this problem myself and when I set it to lib I could enable it just fine.

2021-05-19 14:17 UTC, merged