handle dynamic IP changes
status-im/nim-beacon-chain pull request #3558
Opened 2022-03-30 10:59 UTC by stefantalpalaru

If the external IP was detected through UPnP/NAT-PMP, we check
periodically to see if it changes, then we inform the discovery subsystem
about it.

"nim-eth" is being bumped because it exports a new proc we need in here.

2022-03-30 11:10 UTC, Menduist commented
Just a note, we can also detect IP changes with the libp2p identify protocol (which is used everytime we dial someone/someone dials us)
Currently it's not hooked up, need to be a bit careful because peers can lie to us or other, but it's fully async so at least it won't block the main loop

LMK if you want me to work a bit on that

2022-03-30 11:22 UTC, stefantalpalaru commented
Isn't that the already existing ENT auto update?

2022-03-30 11:25 UTC, Menduist commented
I think the current auto update comes from the DHT, but don't quote me on that

2022-03-30 11:42 UTC, stefantalpalaru commented
Right, but it's the same level of peer trusting which can't be enabled by default. This can.

2022-03-30 12:36 UTC, kdeme commented on beacon_chain/networking/eth2_network.nim
> +          externalTcpPort, externalUdpPort: Option[Port]): T {.raises: [Defect, CatchableError].} =
The ip, udpPort and tcpPort parameters are already considered as external ip and ports. They are the ones that end up in the ENR that is used by discoveryv5. So I think you can just reuse those parameters to set to the object fields.

2022-03-30 12:36 UTC, kdeme commented on beacon_chain/networking/eth2_network.nim
> +  if extIp.isSome() and not config.nat.hasExtIp and config.nat.nat in [NatAny, NatUpnp, NatPmp]:
The downside of this way of selecting it is that if `NatAny` is selected, and this is the default, but there is no actual UPnP or NAT-PMP available, this loop will keep trying to get the external IP every 10 mins.

2022-03-30 12:36 UTC, kdeme commented on beacon_chain/networking/eth2_network.nim
> +      # and blocking the main event loop while we chat with the router.
How long does this block if the request times out?

2022-03-30 13:56 UTC, stefantalpalaru commented on beacon_chain/networking/eth2_network.nim
> +  if extIp.isSome() and not config.nat.hasExtIp and config.nat.nat in [NatAny, NatUpnp, NatPmp]:
Not an issue, because `extIp.isSome()` is only true if one of those mechanisms worked and gave us an external IP.

2022-03-30 14:01 UTC, stefantalpalaru commented on beacon_chain/networking/eth2_network.nim
> +      # and blocking the main event loop while we chat with the router.
3.755s: https://github.com/miniupnp/libnatpmp/pull/15
and https://github.com/status-im/nimbus-build-system/blob/a8ab2dc39aad4d69ba3be72868772d851b4b9741/makefiles/targets.mk#L140

2022-03-30 14:03 UTC, stefantalpalaru commented on beacon_chain/networking/eth2_network.nim
> +          externalTcpPort, externalUdpPort: Option[Port]): T {.raises: [Defect, CatchableError].} =
Fixed.

2022-03-30 14:47 UTC, kdeme commented on beacon_chain/networking/eth2_network.nim
> +  if extIp.isSome() and not config.nat.hasExtIp and config.nat.nat in [NatAny, NatUpnp, NatPmp]:
That would be true for the `setupNat` proc, but with `setupAddress` the bindIp and the best route IP are checked whether they are a public IP address.

2022-03-30 14:56 UTC, arnetheduck commented on beacon_chain/networking/eth2_network.nim
> +      let extIpRes = getExternalIP(config.nat.nat, quiet = true)
this is a synchronous operation? it freezes until router responds?

2022-03-30 14:56 UTC, arnetheduck commented on beacon_chain/networking/eth2_network.nim
> +      # and blocking the main event loop while we chat with the router.
3-4 s is not acceptable, that's enough to lose an attestation slot

2022-03-30 17:20 UTC, stefantalpalaru commented on beacon_chain/networking/eth2_network.nim
> +      let extIpRes = getExternalIP(config.nat.nat, quiet = true)
Yes.

2022-03-30 17:26 UTC, stefantalpalaru commented on beacon_chain/networking/eth2_network.nim
> +  if extIp.isSome() and not config.nat.hasExtIp and config.nat.nat in [NatAny, NatUpnp, NatPmp]:
How about adding the same lookup for a public default route in `getExternalIP()`, since the "nat" module is no longer just about NAT?

2022-03-30 20:57 UTC, stefantalpalaru commented on beacon_chain/networking/eth2_network.nim
> +  if extIp.isSome() and not config.nat.hasExtIp and config.nat.nat in [NatAny, NatUpnp, NatPmp]:
This is what I came up with: https://github.com/status-im/nim-eth/pull/496

2022-03-31 14:11 UTC, stefantalpalaru commented
Prevented delay when a public IP was detected from the routing table.

2022-04-04 11:54 UTC, arnetheduck requested changes
This PR needs updating such that it doesn't block for seconds on the unhappy path (timeout) as this can disrupt attestation work due to how long the timeouts are

2023-04-18 06:10 UTC, arnetheduck commented
closing this since external dynamic ip changes are (mostly) handled by `enr-auto-update` - an async version of this PR would however be nice / accepted

2023-04-18 06:10 UTC, closed without merging