Initial dummy commit
status-im/nim-beacon-chain pull request #6443
Opened 2024-07-23 12:11 UTC by Tomi-3-0

2024-07-27 19:29 UTC, tersec commented on beacon_chain/spec/datatypes/constants.nim
> +  DOMAIN_TYPE_ATTESTER* = DomainType([byte 0x0C, 0x00, 0x00, 0x00])
https://github.com/ethereum/consensus-specs/blob/1508f51b80df5488a515bfedf486f98435200e02/specs/_features/eipxxxx/beacon-chain.md#domain-types calls this a `DOMAIN_PTC_ATTESTER`

2024-07-27 19:31 UTC, tersec commented on beacon_chain/spec/presets/mainnet/epbs_preset.nim
> +# Copyright (c) 2023-2024 Status Research & Development GmbH
None of these files existed before 2024, and the starting year used is somewhat inconsistent across this PR. Probably better to just use
```
Copyright (c) 2024 Status Research & Development GmbH
```
for all the copyright years to start with, more consistent in the PR

2024-07-27 19:32 UTC, tersec commented on beacon_chain/spec/presets/minimal/epbs_preset.nim
> +# Mainnet preset - epbs
This is the minimal preset though?

2024-07-28 06:35 UTC, Tomi-3-0 commented on beacon_chain/spec/presets/minimal/epbs_preset.nim
> +# Mainnet preset - epbs
Ohhh, yes

2024-08-02 23:53 UTC, tersec commented on beacon_chain/spec/datatypes/epbs.nim
> +# Types specific to phase0 (i.e. known to have changed across hard forks) - see
This "types specific to phase 0" comment block doesn't apply here. Types specific to EIP-7732, perhaps.

2024-08-03 00:02 UTC, tersec commented on beacon_chain/spec/ptc_status.nim
> +# Copyright (c) 2018-2024 Status Research & Development GmbH
```suggestion
# Copyright (c) 2024 Status Research & Development GmbH
```
also inconsistent with other copyright headers here otherwise

2024-08-03 00:04 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +  result = false
```suggestion
  false
```
see https://status-im.github.io/nim-style-guide/language.result.html

2024-08-03 00:13 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +{.push raises: [].}
Needs the copyright header

2024-08-06 05:03 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +  let indicesSeq = indices.toSeq()
Basically this whole section is kind of inefficient both algorithmically (O(n log n) rather than O(n)) and more importantly in terms of memory copies and allocation, and therefore garbage collection pressure.

There's already a template implemented elsewhere `is_sorted_and_unique` which checks for these conditions in linear time in constant space, with no additional copies:
https://github.com/status-im/nimbus-eth2/blob/99f657e548162767e354b3be00c336116d69a97b/beacon_chain/spec/beaconstate.nim#L549-L567

It's 7 lines of code, which isn't too bad to just copy, but could also factor it out and reuse it.

2024-08-06 05:05 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +  let indicesSeq = indices.toSeq()
Also, see where `is_valid_indexed_attestation` (the analogous non-ePBS version of this function) lives -- at some point it might be worth looking at how these should be best factored, though for the moment it's fine/useful to have ePBS live largely in separate modules to avoid hindering updating based on `unstable` rather than mixing it throughout.

2024-08-06 05:07 UTC, tersec commented on beacon_chain/spec/helpers.nim
> +
This (and some other in this PR) modules end in several blank/empty lines, which should be avoided

2024-08-06 05:09 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +  # Check if ``indexed_payload_attestation`` is not empty, has sorted and unique indices, and has a valid aggregate signature.
https://status-im.github.io/nim-style-guide/formatting.style.html
> We strive to follow [NEP-1](https://nim-lang.org/docs/nep1.html) for style matters - naming, capitalization, 80-character limit etc.

This comment line is quite a bit longer than 80 characters.

This doesn't mean split (break) all the URLs, etc, or other things which for intrinsic reasons just must have longer than 80 character lines, but where it's feasible/practical to wrap at 80, that's the goal.

2024-08-06 05:11 UTC, tersec commented on beacon_chain/spec/helpers.nim
> +    uint64(fastLog2(n) + 1)
This function claims to return `SomeInteger` but it will always return specifically a `uint64` because of this, so it might be more descriptive/useful to change the return type of the function to be consistent with the `uint64` type of this `if` expression.

2024-08-06 05:14 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +  return blsFastAggregateVerify(pubkeys, signing_root.data, indexed_payload_attestation.signature)
Also quite a bit longer than 80 characters (omitting `return ` would shorten it by 7 and probably be an improvement anyway, but that's still longer than it should be for one line), per style guidelines

2024-08-06 05:18 UTC, tersec commented on beacon_chain/spec/helpers.nim
> +    return 1
It's a bit odd to use the explicit return (`return 1`) in one branch of the `if` statement and in the other branch use the expression return `uint64(...)`. Better to be consistent here (e.g., by using expression return here too and omitting `return `)

2024-08-06 05:24 UTC, tersec commented on beacon_chain/spec/helpers.nim
> +  doAssert n >= 0'u64
```python
def bit_floor(n: uint64) -> uint64:
    """
    if ``n`` is not zero, returns the largest power of `2` that is not greater than `n`.
    """
    if n == 0:
        return 0
    return uint64(1) << (n.bit_length() - 1)
```
explicitly states this should take a `uint64` and return a `uint64`, not whatever random `SomeInteger`. If requires this to at least be unsigned, then can avoid this `doAssert n >= 0'u64` entirely.

Also, because of this assertion's comparison, it won't even work properly with certain `SomeInteger` types, because this `>=` operator depends on the types matching sufficiently. So, e.g., if one uses `bit_floor` with an `int16`:
```
Error: type mismatch
Expression: 0'u64 <= 0'i16
  [1] 0'u64: uint64
  [2] 0'i16: int16

Expected one of (first mismatch at [position]):
[1] proc `<=`(x, y: bool): bool
[1] proc `<=`(x, y: char): bool
[1] proc `<=`(x, y: float): bool
[1] proc `<=`(x, y: float32): bool
[1] proc `<=`(x, y: int): bool
[1] proc `<=`(x, y: int16): bool
[1] proc `<=`(x, y: int32): bool
[1] proc `<=`(x, y: int64): bool
[1] proc `<=`(x, y: int8): bool
[1] proc `<=`(x, y: pointer): bool
[1] proc `<=`(x, y: string): bool
[1] proc `<=`(x, y: uint16): bool
[1] proc `<=`(x, y: uint32): bool
[1] proc `<=`(x, y: uint8): bool
[1] proc `<=`[Enum: enum](x, y: Enum): bool
[1] proc `<=`[T: tuple](x, y: T): bool
[1] proc `<=`[T](x, y: ref T): bool
[1] proc `<=`[T](x, y: set[T]): bool
[2] proc `<=`(x, y: uint): bool
[2] proc `<=`(x, y: uint64): bool
```
similar with any other signed `int` type (`int`, `int8`, `int32`, or `int64`) covered by `SomeInteger`.

So for exactly the types that this function works for already, the assertion is pointless (unsigned are always `>= 0`) and for those the assertion would catch, it would do so by failing to compile with a type error.

The function should instead be more specific about the types it actually accepts and skip the pointless `doAssert`

2024-08-06 11:53 UTC, Tomi-3-0 commented on beacon_chain/spec/payload_attestations.nim
> +  # Check if ``indexed_payload_attestation`` is not empty, has sorted and unique indices, and has a valid aggregate signature.
I forgot to call `nimpretty` on them. Thank you

2024-08-06 12:46 UTC, tersec commented
> Merge branch 'status-im:stable' into epbs 

the development branches should generally track `unstable`, not `stable`

2024-08-06 12:51 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +  # Check if ``indexed_payload_attestation`` is not empty, has sorted and unique indices, and has a valid aggregate signature.
Regarding `nimpretty`, see https://status-im.github.io/nim-style-guide/formatting.style.html#practical-notes
> - We do not use nimpretty - as of writing (Nim 1.6), it is not stable enough for daily use:
>
>   - Can break working code
>   - Naive formatting algorithm

if it works for you, that's great, but it has many flaws, so shouldn't be trusted too much, and shouldn't be used to reformat existing Nimbus code.

2024-08-06 13:05 UTC, Tomi-3-0 commented
> > Merge branch 'status-im:stable' into epbs
> 
> the development branches should generally track `unstable`, not `stable`

tracks unstable from my end:
`...wants to merge 22 commits into status-im:unstable from Tomi-3-0:epbs`

2024-08-07 14:50 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +proc is_parent_block_full(state: epbs.BeaconState) : bool =
https://status-im.github.io/nim-style-guide/language.proc.html#functions-and-procedures-languageproc
> Prefer `func` - use `proc` when side effects cannot conveniently be avoided.

But here there aren't any side effects, so `func` works fine

2024-08-07 14:51 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +# # https://github.com/ethereum/consensus-specs/blob/1508f51b80df5488a515bfedf486f98435200e02/specs/_features/eipxxxx/beacon-chain.md#is_parent_block_full
is the `# # https://...` intentional?

2024-08-08 04:04 UTC, Tomi-3-0 commented on beacon_chain/spec/payload_attestations.nim
> +proc is_parent_block_full(state: epbs.BeaconState) : bool =
Noted

2024-08-11 03:17 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +  result = output
https://status-im.github.io/nim-style-guide/language.result.html

2024-08-11 03:18 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +  result = output.filterIt(it notin ptc)
https://status-im.github.io/nim-style-guide/language.result.html

2024-08-11 03:18 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +  result = IndexedPayloadAttestation(
https://status-im.github.io/nim-style-guide/language.result.html

2024-08-11 03:21 UTC, tersec commented
Are the deletions of `NimYAML`, `gnosis-chain-configs`, `nim-libbacktrace`, `nim-libp2p`, and `sepolia` vendored git subrepositories intentional?

![2024-08-11T03:19:16,587536883+00:00](https://github.com/user-attachments/assets/8f02d56d-6599-47b1-af5b-aaca7ff66d79)

2024-08-11 03:29 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +    output = initHashSet[ValidatorIndex]()
https://nim-lang.org/docs/sets.html#initHashSet
> Starting from Nim v0.20, sets are initialized by default and it is not necessary to call this function explicitly.

2024-08-11 03:32 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +# https://github.com/ethereum/consensus-specs/blob/1508f51b80df5488a515bfedf486f98435200e02/specs/_features/eipxxxx/beacon-chain.md#get_indexed_payload_attestation
Now available as https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.4/specs/_features/eip7732/beacon-chain.md#get_indexed_payload_attestation

2024-08-11 03:33 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +# https://github.com/ethereum/consensus-specs/blob/1508f51b80df5488a515bfedf486f98435200e02/specs/_features/eipxxxx/beacon-chain.md#get_payload_attesting_indices
Now available as https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.4/specs/_features/eip7732/beacon-chain.md#get_payload_attesting_indices

2024-08-11 03:36 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +# https://github.com/ethereum/consensus-specs/blob/1508f51b80df5488a515bfedf486f98435200e02/specs/_features/eipxxxx/beacon-chain.md#modified-get_attesting_indices
https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.4/specs/_features/eip7732/beacon-chain.md#modified-get_attesting_indices but it has a couple of changes vs the one here

- it adds `committee_offset += len(committee)` to the `for` loop; and
- it adds an early exit condition
```python
    if compute_epoch_at_slot(attestation.data.slot) < EIP7732_FORK_EPOCH:
        return output
```
before the `get_ptc()` call.

2024-08-11 03:38 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +# https://github.com/ethereum/consensus-specs/blob/1508f51b80df5488a515bfedf486f98435200e02/specs/_features/eipxxxx/beacon-chain.md#get_ptc
https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.4/specs/_features/eip7732/beacon-chain.md#get_ptc (no substantial changes, can just update URL)

2024-08-11 03:38 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +# https://github.com/ethereum/consensus-specs/blob/1508f51b80df5488a515bfedf486f98435200e02/specs/_features/eipxxxx/beacon-chain.md#is_parent_block_full
https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.4/specs/_features/eip7732/beacon-chain.md#is_parent_block_full (no changes, can just update URL)

2024-08-11 03:40 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +# https://github.com/ethereum/consensus-specs/blob/1508f51b80df5488a515bfedf486f98435200e02/specs/_features/eipxxxx/beacon-chain.md#predicates
https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.4/specs/_features/eip7732/beacon-chain.md#is_valid_indexed_payload_attestation (only trivial/cosmetic reformatting, can just update URL)

2024-08-11 03:45 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +    output = initHashSet[ValidatorIndex]()
Does this even compile? It creates a `HashSet` as a `let` (immutable) variable, then tries to mutate it.

```nim
import std/sets

proc get_payload_attesting_indices(): HashSet[int] =
  let output = initHashSet[int]()

  output.incl(0)

  result = output
```
results in
```
Error: type mismatch
Expression: incl(output, 0)
  [1] output: HashSet[system.int]
  [2] 0: int literal(0)

Expected one of (first mismatch at [position]):
[1] func incl[T](x: var set[T]; y: T)
[1] proc incl[A](s: var HashSet[A]; key: A)
  expression 'output' is immutable, not 'var'
[1] proc incl[A](s: var HashSet[A]; other: HashSet[A])
  expression 'output' is immutable, not 'var'
[1] proc incl[A](s: var HashSet[A]; other: OrderedSet[A])
  expression 'output' is immutable, not 'var'
[1] proc incl[A](s: var OrderedSet[A]; key: A)
[1] template incl[T](x: var set[T]; y: set[T])
```

A mutated, non-`ref` variable needs to be declared as `var`

2024-08-11 23:15 UTC, Tomi-3-0 commented
> Are the deletions of `NimYAML`, `gnosis-chain-configs`, `nim-libbacktrace`, `nim-libp2p`, and `sepolia` vendored git subrepositories intentional?
> 
> ![2024-08-11T03:19:16,587536883+00:00](https://private-user-images.githubusercontent.com/11422416/356848090-8f02d56d-6599-47b1-af5b-aaca7ff66d79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MTgzMjQsIm5iZiI6MTcyMzQxODAyNCwicGF0aCI6Ii8xMTQyMjQxNi8zNTY4NDgwOTAtOGYwMmQ1NmQtNjU5OS00N2IxLWFmNWItYWFjYTdmZjY2ZDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDIzMTM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MWFmZDNhMWVjZTVmNTMzNzRjNThlMTU3ZjFhNWM3MDk0ZTg5ZjZlY2YwYjFiYTc3MTAyMzA5ZGQ4OTUwZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tg-6GfrSA0NMTGON6A6NwnTh8oBwAb6SqJSXkLk-2E8)

Yes, they are. Not sure if I was supposed to push those on to github

2024-08-11 23:27 UTC, Tomi-3-0 commented on beacon_chain/spec/payload_attestations.nim
> +    output = initHashSet[ValidatorIndex]()
> Does this compile? It creates a `HashSet` as a `let` (immutable) variable, then tries to mutate it.
> 
> ```nim
> import std/sets
> 
> proc get_payload_attesting_indices(): HashSet[int] =
>   let output = initHashSet[int]()
> 
>   output.incl(0)
> 
>   result = output
> ```
> 
> results in
> 
> ```
> Error: type mismatch
> Expression: incl(output, 0)
>   [1] output: HashSet[system.int]
>   [2] 0: int literal(0)
> 
> Expected one of (first mismatch at [position]):
> [1] func incl[T](x: var set[T]; y: T)
> [1] proc incl[A](s: var HashSet[A]; key: A)
>   expression 'output' is immutable, not 'var'
> [1] proc incl[A](s: var HashSet[A]; other: HashSet[A])
>   expression 'output' is immutable, not 'var'
> [1] proc incl[A](s: var HashSet[A]; other: OrderedSet[A])
>   expression 'output' is immutable, not 'var'
> [1] proc incl[A](s: var OrderedSet[A]; key: A)
> [1] template incl[T](x: var set[T]; y: set[T])
> ```
> 
> A mutated, non-`ref` variable needs to be declared as `var`

It does compile on my end. Not sure why

2024-08-12 00:02 UTC, tersec commented
> > Are the deletions of `NimYAML`, `gnosis-chain-configs`, `nim-libbacktrace`, `nim-libp2p`, and `sepolia` vendored git subrepositories intentional?
> > ![2024-08-11T03:19:16,587536883+00:00](https://private-user-images.githubusercontent.com/11422416/356848090-8f02d56d-6599-47b1-af5b-aaca7ff66d79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MTgzMjQsIm5iZiI6MTcyMzQxODAyNCwicGF0aCI6Ii8xMTQyMjQxNi8zNTY4NDgwOTAtOGYwMmQ1NmQtNjU5OS00N2IxLWFmNWItYWFjYTdmZjY2ZDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDIzMTM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MWFmZDNhMWVjZTVmNTMzNzRjNThlMTU3ZjFhNWM3MDk0ZTg5ZjZlY2YwYjFiYTc3MTAyMzA5ZGQ4OTUwZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tg-6GfrSA0NMTGON6A6NwnTh8oBwAb6SqJSXkLk-2E8)
> 
> Yes, they are. Not sure if I was supposed to push those on to github

Well, this branch/PR/commit sequence should contain the changes, and unless you're changing those dependencies, they should be left unaltered. That is, by keeping them around, you're not pushing them onto GitHub exactly [1, for caveats, but this is conceptually true for how one generally uses Git].

As is, if one just merges this branch into `unstable` it will break the `unstable` branch and makes it trickier to review and to update/rebase/merge into newer versions of `unstable`.
- for example, by removing `nimbus-build-system`, it means that the only reason the branch can work at all is that one has already built `nimbus-build-system` while checked out to another branch/commit, which has not removed it. Otherwise there's just no Nim compiler for it to use.
- by removing `sepolia`, you're creating an artificial merge conflict unrelated to the substantive contents of this PR, because there was a `sepolia` update:
![2024-08-11T23:59:31,930163907+00:00](https://github.com/user-attachments/assets/94989daa-f609-40cf-ba39-2c720cf348a3)
and because of that, several of the CIs can't run (because they first rebase things to `unstable`).

So it doesn't help and does hinder development to remove some of the subrepositories in this PR.

[1] Well, at some level, sort of are: one can look up details of how Git stores submodule information and how it stores files when they're uploaded each time as part of a commit. The short version is, it uses a kind of sorting then run-length compression of identical blob [read: file, sort of] contents in a way which makes the additional commit's "copy" basically free. So at a sufficiently [plumbing](https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain) level, yes, it's uploading pointers-to-subrepositories, but at a porcelain level, that's how Git works, and it's more disruptive to overall workflows to remove files than do nothing at all.

2024-08-12 00:46 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +    output = initHashSet[ValidatorIndex]()
It's because it's generic (`ForkyBeaconState`) so until you try to instantiate any particular version of that function by calling it, it does only minimal type checking on it. Same with various other functions getting a `ForkyBeaconState`.

But by calling it, one doesn't even get that far though:
```
nimbus-eth2$ ./env.sh nim c beacon_chain/spec/payload_attestations.nim
...
nimbus-eth2/beacon_chain/spec/payload_attestations.nim(119, 38) template/generic instantiation of `get_payload_attesting_indices` from here
nimbus-eth2/beacon_chain/spec/payload_attestations.nim(109, 18) template/generic instantiation of `get_ptc` from here
nimbus-eth2/beacon_chain/spec/payload_attestations.nim(66, 69) Error: type mismatch
Expression: get_committee_count_per_slot(state, epoch)
  [1] state: BeaconState
  [2] epoch: Epoch

Expected one of (first mismatch at [position]):
[1] func get_committee_count_per_slot(num_active_validators: uint64): uint64
[1] func get_committee_count_per_slot(state: ForkedHashedBeaconState; epoch: Epoch;
                                  cache: var StateCache): uint64
[3] func get_committee_count_per_slot(state: ForkyBeaconState; epoch: Epoch;
                                  cache: var StateCache): uint64
  missing parameter: cache
```
with just a minimal caller set up:
```
diff --git a/beacon_chain/spec/payload_attestations.nim b/beacon_chain/spec/payload_attestations.nim
index 9f428739b..8326997e5 100644
--- a/beacon_chain/spec/payload_attestations.nim
+++ b/beacon_chain/spec/payload_attestations.nim
@@ -115,6 +115,9 @@ proc get_payload_attesting_indices(state: var ForkyBeaconState, slot: Slot,
 
   result = output
 
+var foo: electra.BeaconState
+discard get_payload_attesting_indices(foo, 0.Slot, default(PayloadAttestation))
+
 # https://github.com/ethereum/consensus-specs/blob/1508f51b80df5488a515bfedf486f98435200e02/specs/_features/eipxxxx/beacon-chain.md#get_indexed_payload_attestation
 proc get_indexed_payload_attestation(state: var ForkyBeaconState, slot: Slot,
     payload_attestation: PayloadAttestation): IndexedPayloadAttestation =
```
One can see the same error message by instead of using `ForkyBeaconState`, a generic typeclass, one uses the concrete type `electra.BeaconState` instead:
```
diff --git a/beacon_chain/spec/payload_attestations.nim b/beacon_chain/spec/payload_attestations.nim
index 9f428739b..55ea639d2 100644
--- a/beacon_chain/spec/payload_attestations.nim
+++ b/beacon_chain/spec/payload_attestations.nim
@@ -101,7 +101,7 @@ proc get_attesting_indices(state: var ForkyBeaconState,
   result = output.filterIt(it notin ptc)
 
 # https://github.com/ethereum/consensus-specs/blob/1508f51b80df5488a515bfedf486f98435200e02/specs/_features/eipxxxx/beacon-chain.md#get_payload_attesting_indices
-proc get_payload_attesting_indices(state: var ForkyBeaconState, slot: Slot,
+proc get_payload_attesting_indices(state: var electra.BeaconState, slot: Slot,
     payload_attestation: PayloadAttestation): HashSet[
         ValidatorIndex] =

```

So there are a couple of possible approaches, of which one should probably do at least one:
- figure out if some of these functions really don't apply to all `ForkyBeaconState`s, but rather specifically only to one kind of `ForkyBeaconState`, for example, `epbs.BeaconState`. Then the `get_payload_attesting_indices`, `get_ptc`, and other relevant functions (which indeed don't actually apply to non-ePBS states) have not generic (`ForkyBeaconState`, which defers most typechecking until there are callers) but concrete `BeaconState` (which typechecks immediately); and/or
- add example calling code along the lines of what I used above -- even just two lines of code with default values, because the point here isn't to produce correct results, but to ensure the types are set up correctly, so just `default(FooType)` suffices.

2024-08-12 00:48 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +    output = initHashSet[ValidatorIndex]()
if you want to make sure the example calling code doesn't compile accidentally, one can:
- use `when isMainModule`:
```nim
when isMainModule:
  echo "this only runs when the module is the main module, not imported by some other module"
```
or
add some basic sanity tests in `tests/` which call each of your functions with values of appropriate types.

2024-08-12 07:11 UTC, Tomi-3-0 commented
> > > Are the deletions of `NimYAML`, `gnosis-chain-configs`, `nim-libbacktrace`, `nim-libp2p`, and `sepolia` vendored git subrepositories intentional?
> > > ![2024-08-11T03:19:16,587536883+00:00](https://private-user-images.githubusercontent.com/11422416/356848090-8f02d56d-6599-47b1-af5b-aaca7ff66d79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MTgzMjQsIm5iZiI6MTcyMzQxODAyNCwicGF0aCI6Ii8xMTQyMjQxNi8zNTY4NDgwOTAtOGYwMmQ1NmQtNjU5OS00N2IxLWFmNWItYWFjYTdmZjY2ZDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDIzMTM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MWFmZDNhMWVjZTVmNTMzNzRjNThlMTU3ZjFhNWM3MDk0ZTg5ZjZlY2YwYjFiYTc3MTAyMzA5ZGQ4OTUwZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tg-6GfrSA0NMTGON6A6NwnTh8oBwAb6SqJSXkLk-2E8)
> > 
> > Yes, they are. Not sure if I was supposed to push those on to github
> 
> Well, this branch/PR/commit sequence should contain the changes, and unless you're changing those dependencies, they should be left unaltered. That is, by keeping them around, you're not pushing them onto GitHub exactly [1, for caveats, but this is conceptually true for how one generally uses Git].
> 
> As is, if one just merges this branch into `unstable` it will break the `unstable` branch and makes it trickier to review and to update/rebase/merge into newer versions of `unstable`.
> - when one runs `./env.sh nim c beacon_chain/spec/payload_attestations.nim`, it displays the errors:
> ```
> /usr/bin/ld: cannot find nimbus-eth2/vendor/nim-libbacktrace/install/usr/lib/libbacktracenim.a: No such file or directory
> /usr/bin/ld: cannot find nimbus-eth2/vendor/nim-libbacktrace/install/usr/lib/libbacktrace.a: No such file or directory
> collect2: error: ld returned 1 exit status
> ```
> and does not properly build because of the removal of `nim-libbacktrace`
> - by removing `sepolia`, you're creating an artificial merge conflict unrelated to the substantive contents of this PR, because there was a `sepolia` update:
> ![2024-08-11T23:59:31,930163907+00:00](https://github.com/user-attachments/assets/94989daa-f609-40cf-ba39-2c720cf348a3)
> and because of that, several of the CIs can't run (because they first rebase things to `unstable`).
> 
> So it doesn't help and does hinder development to remove some of the subrepositories in this PR.
> 
> [1] Well, at some level, sort of are: one can look up details of how Git stores submodule information and how it stores files when they're uploaded each time as part of a commit. The short version is, it uses a kind of sorting then run-length compression of identical blob [read: file, sort of] contents in a way which makes the additional commit's "copy" basically free. So at a sufficiently [plumbing](https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain) level, yes, it's uploading pointers-to-subrepositories, but at a porcelain level, that's how Git works, and it's more disruptive to overall workflows to remove files than do nothing at all.

So detailed. Thank you

2024-08-15 15:53 UTC, tersec commented
The CI still isn't running, partly because of the merge conflicts.
![2024-08-15T15:41:02,100365934+00:00](https://github.com/user-attachments/assets/c1af92b9-48d1-4fcb-9497-2f0c02ff26fa)

https://github.com/status-im/nimbus-eth2/pull/6443/commits/b922f277ab3c2b920a9b9e681e034752a82919d0 does add back the removed submodules, but doesn't fully address `sepolia`; if nothing else, it seems to move all five submodules to slightly different commits than they started from:
![2024-08-15T15:40:08,096645337+00:00](https://github.com/user-attachments/assets/224393f2-bb4c-45f1-bdcd-baa653639479)

2024-08-15 15:55 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +      output = [ValidatorIndex]()
Does this compile? It's a generic function (`var ForkyBeaconState`), so it might not notice it  immediately, but I'm not sure what this line is supposed to do/mean

2024-08-15 15:57 UTC, tersec commented on beacon_chain/spec/datatypes/constants.nim
> +  # https://github.com/ethereum/consensus-specs/blob/1508f51b80df5488a515bfedf486f98435200e02/specs/_features/eipxxxx/beacon-chain.md#domain-types [New in epbs]
https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.4/specs/_features/eip7732/beacon-chain.md#domain-types

2024-08-15 15:58 UTC, tersec commented on beacon_chain/spec/datatypes/epbs.nim
> +  # https://github.com/ethereum/consensus-specs/blob/1508f51b80df5488a515bfedf486f98435200e02/specs/_features/eipxxxx/beacon-chain.md#payloadattestationdata
https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.4/specs/_features/eip7732/beacon-chain.md#payloadattestationdata (is exact same, can just update URL)

2024-08-18 07:18 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    assert verify_execution_payload_header_signature(state, signed_header)
I'm aware the Ethereum consensus layer executable spec phrases these as `assert`, but we (a) use `doAssert` in Nim for `assert`, because [`assert`](https://nim-lang.org/docs/assertions.html#assert.t%2Cuntyped%2Cstring) doesn't run under certain build settings, while [`doAssert`](https://nim-lang.org/docs/assertions.html#doAssert.t%2Cuntyped%2Cstring) does.

Beyond that though, in this case, they shouldn't use either (Nim) `assert` or `doAssert`, but rather return a failure. Not having a specified return type (again, I'm aware, that's how the executable spec phrases this, and you've copied that faithfully into Nim as far as it goes) is `void`, while it should instead be `Result[void, cstring]`, which would allow for failure return values.

https://github.com/status-im/nimbus-eth2/blob/b511f3eeb7982cb84f8aa4ad08fbec310b4693f7/beacon_chain/spec/state_transition_block.nim#L43-L79

is a good model here. Some salient points:
- even though its spec version is defined similarly, with no explicit return value and `assert`s, here those `asserts` turn into checks for the asserted condition, and `return err("some informative message")` instead. Actual assertions would kill the `nimbus_beacon_node` process, and that's definitely not desirable as a response to invalid network input;

- because `default(Result[void, cstring]))` is an error, not success, value, at the end it uses implicit return (no `return foo`, just `foo` at end of function) to return `ok()`, i.e. if it didn't fail, it succeeded;

-  all of those messages are literal, constant strings, because `cstring` isn't being runtime-constructed here, but compile-time, and this makes it more efficient. In some cases, it might be worth having runtime construction of an error message, but typically that'd be at a higher level of the call stack, where logging might happen; and

- it uses the `if not condition` even when the condition is trivial to switch (`==` vs `!=` for example) for uniformity/correspondence with spec phrasing, because the spec providers the expected version, not the version under which it should exit early.

2024-08-18 07:20 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +proc process_execution_payload_header*(state: var ForkyBeaconState,
Does `process_execution_payload_header` work with any other `BeaconState` type except `epbs.BeaconState`? See elsewhere about the hazards of using a generic typeclass here `ForkyBeaconState` insofar as it defers typechecking.

2024-08-18 07:24 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +proc verify_execution_payload_header_signature*(state: epbs.BeaconState,
These `verify_foo_signature` functions tend to go in https://github.com/status-im/nimbus-eth2/blob/unstable/beacon_chain/spec/signatures.nim

Also, typically they have the `compute_foo_signing_root` part factored out, e.g., everything here up through `let signing_root = ...` would be part of this `compute_foo_signing_root` function, then the `verify_foo_signature` version would call this `compute_foo_signing_root` part, the run `blsVerify` on it. This is especially useful when Nimbus also has to sign such messages, because then it can re-use the `compute_foo_signing_root` part entirely.

2024-08-18 07:25 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    state: var (capella.BeaconState | deneb.BeaconState | electra.BeaconState |
Functions already exist which cover `capella.beaconState`, `deneb.BeaconState`, and `electra.BeaconState`. This should only match `epbs.BeaconState`, and probably it'll be a compiler error regardless otherwise.

2024-08-18 07:26 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    when typeof(state).kind >= ConsensusFork.Electra:
Therefore, since `epbs.BeaconState` would imply `typeof(state).kind >= ConsensusFork.Electra`, this section would be unconditionally present.

2024-08-18 07:29 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +from ".."/validator_bucket_sort import
This should be short enough to all be on one line (<= 80 characters)

2024-08-18 07:32 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    state: var (capella.BeaconState | deneb.BeaconState | electra.BeaconState |
Also, more generally, as of https://github.com/status-im/nimbus-eth2/pull/6470 Nimbus does some trickery around withdrawals to support certain more efficient operations. It's okay to ignore this for now though.

2024-08-18 07:40 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    cfg: RuntimeConfig, state: var ForkyBeaconState,
Overloads/specializations of `process_operations` already exist for all `ForkyBeaconState`s through `electra`. The new version should only be defined as for `epbs.BeaconState`, not all `ForkyBeaconState`.

2024-08-18 07:41 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    when typeof(body).kind >= ConsensusFork.Epbs:
Which means it would not need these `when typeof(body.kind) >= ConsensusFork.Foo` checks, any any `Foo` up to and including `Epbs`.

2024-08-18 07:45 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +# https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.4/specs/_features/eip7732/beacon-chain.md#modified-validate_merge_block
Hm, have to figure out the priority/relevance of these. It might be safe to just assume that ePBS can't occur until merged, assert this in `checkForkConsistency`, and
- define `is_merge_transition_complete` as trivially `true` and
- define `validate_merge_block` as true (I guess? whatever causes the least problems)

I'm not sure it's worth supporting these edge cases in Nimbus, will have to discuss this with Potuz. All new (relevant) networks are born merged.

2024-08-18 07:51 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +  proc get_payload_attesting_indices(state: var ForkyBeaconState, slot: Slot,
For all these ePBS-specific functions operating on some `BeaconState` (also `get_indexed_payload_attestation`, `get_ptc`, etc), probably better to specifically use the `epbs.BeaconState` to enable Nim to typecheck earlier and with more useful compiler error messages than `ForkyBeaconState`.

2024-08-18 07:51 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +      output = [ValidatorIndex]()
What does this line do? I'm not sure if that's valid Nim. Does it compile?

2024-08-18 07:55 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +    output.filterIt(it notin ptc)
If `ptc` is used as a lookup table in a loop on `output`, this `notin` an O(n) linear search operation which on average will search half the table. It would be more asymptotically efficient to construct a `HashSet[ValidatorIndex]` from `get_ptc()`s return value and run `notin` on that.

This `let ptc = get_ptc(...); output.filterIt(it notin ptc)` effectively creates an O(n^2) nested, quadratic loop, which Nimbus avoids.

2024-08-18 07:55 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +  proc get_ptc(state: var ForkyBeaconState, slot: Slot): List[
Why is `get_ptc` in `isMainModule`? It's a library function which should be generally available.

2024-08-18 15:38 UTC, Redidacove commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    if not is_parent_block_full(state):
We should only check this for typeof(state.kind) >= ConsensusFork.EPBS

2024-08-18 15:38 UTC, Redidacove commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    when typeof(state).kind >= ConsensusFork.Electra:
I think in prysm I have done it as state.version()>version.EPBS 
You can refer my [PR](https://github.com/prysmaticlabs/prysm/pull/14297).

I explicitly stored expectedwithdrawalroot into state.withdrawalroot for epbs and for pre-epbs states just fetching data from payload and matching with the expected as usual .Making this fn compatible with all the forks

2024-08-18 15:38 UTC, Redidacove commented on beacon_chain/spec/payload_attestations.nim
> +      payload_attestation: PayloadAttestation): HashSet[
Would like to say consider adding a version check for epbs fns like if state.version< version.epbs error out or follow what tersec says use specific beaconstate

2024-08-18 15:38 UTC, Redidacove commented on beacon_chain/spec/payload_attestations.nim
> +      output = [ValidatorIndex]()
He is trying to create an dynamic array of validatorIndex type elements to store the attesting indices which he would get after checking the indices of set bits in ptc.aggregation_bits 
I think should do something like ```var output: seq[ValidatorIndex] = @[]```
after creating a validatorindex type or see how it is defined in nimbus

2024-08-18 15:38 UTC, Redidacove commented on beacon_chain/spec/payload_attestations.nim
> +      if payload_attestation.aggregation_bits[i]:
Not sure if this is properly checking the set bits in aggregation_bits and would suggest naming variable like indices instead of output it makes more sense

2024-08-18 17:51 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +      output = [ValidatorIndex]()
Ok, if so in Nim, `@[]` is the default value of a `seq`, so can just use `var output: seq[ValidatorIndex]`.

2024-08-18 18:20 UTC, tersec commented
CI error from https://github.com/status-im/nimbus-eth2/actions/runs/10436092895/job/28915055678?pr=6443:
```
/github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/networking/network_metadata.nim(312, 53)
/github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/networking/network_metadata.nim(231, 11) loadCompileTimeNetworkMetadata
/github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/networking/network_metadata.nim(231, 11) Error: config.yaml not found for network '/github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/networking/../../vendor/sepolia/metadata
make: *** [Makefile:447: wss_sim] Error 1
```
It's because the `vendor/sepolia` submodule isn't correct.

2024-08-18 21:15 UTC, Tomi-3-0 commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    if not is_parent_block_full(state):
The idea behind this is for it to apply to only epbs states for now

2024-08-18 23:57 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +      payload_attestation: PayloadAttestation): HashSet[
So, Nimbus tries to do things as type-statically as feasible, and the `when foo` checks are compile-time, not runtime. They're effectively a form of compile-time specification.  For the most part, almost nothing here should be using `ForkyBeaconState`, then the checks for specific fork are statically accounted for by the Nim typechecker automatically.

2024-08-20 11:32 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +# https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.4/specs/_features/eip7732/beacon-chain.md#modified-validate_merge_block
Confirmed, these can be approached in the minimal way as described above

2024-08-21 14:16 UTC, tersec commented
Current CI build error from https://github.com/status-im/nimbus-eth2/actions/runs/10485514869/job/29049260286?pr=6443
```
2024-08-21T10:33:59.3219729Z ...................................................../github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/networking/eth2_network.nim(26, 18) Error: cannot open file: libp2p/services/wildcardresolverservice
2024-08-21T10:33:59.4585071Z ........................./github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/networking/eth2_network.nim(26, 18) Error: cannot open file: libp2p/services/wildcardresolverservice
2024-08-21T10:33:59.5158541Z .........make: *** [Makefile:447: mev_mock] Error 1
2024-08-21T10:33:59.5159233Z make: *** Waiting for unfinished jobs....
2024-08-21T10:33:59.6455231Z .......make: *** [Makefile:447: ncli_testnet] Error 1
--
2024-08-21T10:34:06.6268785Z Build completed successfully: build/ncli_split_keystore
2024-08-21T10:34:06.8125123Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/networking/eth2_network.nim(26, 18) Error: cannot open file: libp2p/services/wildcardresolverservice
2024-08-21T10:34:07.0563211Z make: *** [Makefile:447: nimbus_light_client] Error 1
```
i.e. the `nim-libp2p` commit isn't correct and should match what's currently in `unstable`, which does have this `libp2p/services/wildcardresolverservice` module.

2024-08-21 14:28 UTC, Tomi-3-0 commented
Okay

2024-08-22 06:56 UTC, tersec commented
Same issue after https://github.com/status-im/nimbus-eth2/pull/6443/commits/7a8f3d28671381a8c6ee8ec39c6d0bf47528029f
from https://github.com/status-im/nimbus-eth2/actions/runs/10495776698/job/29095113051?pr=6443
```
2024-08-22T06:41:11.3486196Z ....../github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/networking/eth2_network.nim(26, 18) Error: cannot open file: libp2p/services/wildcardresolverservice
2024-08-22T06:41:11.5353221Z make: *** [Makefile:447: mev_mock] Error 1
2024-08-22T06:41:11.5354120Z make: *** Waiting for unfinished jobs....
2024-08-22T06:41:11.7260264Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/networking/eth2_network.nim(26, 18) Error: cannot open file: libp2p/services/wildcardresolverservice
2024-08-22T06:41:11.8989887Z ...................make: *** [Makefile:447: ncli_testnet] Error 1
2024-08-22T06:41:14.4235842Z ................
2024-08-22T06:41:14.4237608Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/vendor/nim-ssz-serialization/ssz_serialization/digest.nim(35, 9) Hint: BLST SHA256 backend enabled [User]
2024-08-22T06:41:14.4245272Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/vendor/nim-ssz-serialization/ssz_serialization/digest.nim(49, 9) Hint: Hashtree SHA256 backend enabled [User]
2024-08-22T06:41:17.9723237Z Hint: mm: refc; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
2024-08-22T06:41:17.9725687Z 261407 lines; 108.718s; 3.389GiB peakmem; proj: /github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/nimbus_validator_client.nim; out: /github-runner/workspace/nimbus-eth2/nimbus-eth2/nimcache/release/nimbus_validator_client/nimbus_validator_client.json [SuccessX]
2024-08-22T06:41:18.4726446Z Build completed successfully: build/ncli
2024-08-22T06:41:19.3225322Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/networking/eth2_network.nim(26, 18) Error: cannot open file: libp2p/services/wildcardresolverservice
2024-08-22T06:41:19.4667763Z Build completed successfully: build/ncli_split_keystore
2024-08-22T06:41:19.5530132Z make: *** [Makefile:447: nimbus_light_client] Error 1
```
Can test this locally by running, e.g., `make nimbus_light_client`.

https://github.com/status-im/nimbus-eth2/tree/unstable/vendor shows what `nim-libp2p` commit `unstable` is expecting: https://github.com/vacp2p/nim-libp2p/tree/b5fb7b3a97d8977d969d786633f70c4094cd0eaf which indeed has https://github.com/vacp2p/nim-libp2p/blob/b5fb7b3a97d8977d969d786633f70c4094cd0eaf/libp2p/services/wildcardresolverservice.nim

2024-08-22 07:40 UTC, Tomi-3-0 commented
Okay.

2024-08-25 05:27 UTC, tersec commented
https://github.com/status-im/nimbus-eth2/actions/runs/10542331340/job/29213098600?pr=6443
```
...
2024-08-25T05:06:54.2440825Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/spec/datatypes/epbs.nim(61, 52) Error: undeclared identifier: 'PTC_SIZE'
2024-08-25T05:06:54.2442766Z candidates (edit distance, scope distance); see '--spellSuggest': 
2024-08-25T05:06:54.2443694Z  (2, 3): 'csize'
2024-08-25T05:06:54.2695466Z make: *** [Makefile:647: gnosis-build] Error 1
...
```
because https://github.com/Tomi-3-0/nimbus-eth2/tree/epbs/beacon_chain/spec/presets/gnosis needs the same `PTC_SIZE` and `MAX_PAYLOAD_ATTESTATIONS` presets as the EF mainnet and minimal ePBS presets.

Practically, it's fine to just copy https://github.com/Tomi-3-0/nimbus-eth2/blob/epbs/beacon_chain/spec/presets/mainnet/epbs_preset.nim for this purpose, maybe replacing "Mainnet preset" comments with "Gnosis preset", but the substantive contents can be identical since as far as I know, Gnosis hasn't taken a position on this so Nimbus just needs reasonable placeholders here for now.

2024-08-25 08:57 UTC, Tomi-3-0 commented
Thanks

2024-08-27 09:17 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +# https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.4/specs/_features/eip7732/beacon-chain.md#get_ptc
At this point, https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.5/specs/_features/eip7732/beacon-chain.md#get_ptc

It's not critical to update every URL here every time there's an alpha consensus spec update, but it's for things you're changing each in a given commit it's still worth using the newest one

2024-08-27 09:20 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +proc get_attesting_indices*(state: var ForkyBeaconState,
Does this apply to any beacon state except an `epbs.BeaconState`?

The concern here is the usual, without something calling all these generic functions it's hard to say if something is missing/incorrect, which, almost certainly is the case in this specific example (`committee_attesters = [ValidatorIndex]()`, noted separately).

2024-08-27 09:20 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +      committee_attesters = [ValidatorIndex]()
I'm not sure this is correct Nim

2024-08-27 09:28 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +        return err("process_execution_payload_header: proposer index out of range")
why all these 2-space-indent to 4-space-indent changes? the code uses 2 space indentation, e.g., based on https://status-im.github.io/nim-style-guide/formatting.style.html and https://nim-lang.org/docs/nep1.html (though for certain blocks Nim uses a tweaked version of NEP-1, effectively, the basic version is still 2 spaces)

they were fine before.

2024-08-27 09:35 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +      committee = get_beacon_committee(state, attestation.data.slot, index)
Which `get_beacon_committee()` is this calling?

Neither
https://github.com/status-im/nimbus-eth2/blob/99f657e548162767e354b3be00c336116d69a97b/beacon_chain/spec/validator.nim#L238-L300
nor
https://github.com/status-im/nimbus-eth2/blob/99f657e548162767e354b3be00c336116d69a97b/beacon_chain/consensus_object_pools/spec_cache.nim#L43-L67
seems to have a matching signature.

2024-08-27 09:42 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +  sequtils, sets, lists,
What is https://nim-lang.org/docs/lists.html used for?

Also, in general, prefer `std/sequtils` and `std/sets` to just `sequtils` and `sets`

2024-08-27 09:44 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +    validator_indices: seq[ValidatorIndex]
Can use [`newSeq`](https://nim-lang.org/docs/system.html#newSeq) to directly create a sequence of a given length, rather than the default 0-length sequence which is immediately resized with `setLen` as here

2024-08-27 09:44 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +  # instead of iterator
Why might one need to do this?

2024-08-27 09:45 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +  output.filterIt(it notin ptc)
Still O(n^2)

2024-08-27 10:33 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    sequtils,
Prefer `std/sequtils`

2024-08-27 10:33 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +            payload_attestations, ],
Why is `payload_attestations` imported twice, here and two lines later?

2024-08-27 21:23 UTC, Tomi-3-0 commented on beacon_chain/spec/state_transition_block_epbs.nim
> +            payload_attestations, ],
an oversight, thank you

2024-08-27 21:28 UTC, Tomi-3-0 commented on beacon_chain/spec/payload_attestations.nim
> +  # instead of iterator
My initial thought was that the iterator wasn't meant for specific hardfork (e.g epbs.BeaconState) states but generalised ForkyBeaconState

2024-09-09 16:14 UTC, tersec commented
https://github.com/status-im/nimbus-eth2/actions/runs/10752309189/job/29884832856?pr=6443
```
2024-09-09T16:08:28.1595661Z stack trace: (most recent call last)
2024-09-09T16:08:28.1599116Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/networking/network_metadata.nim(324, 11) network_metadata
2024-09-09T16:08:28.1602221Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/std/assertions.nim(41, 14) failedAssertImpl
2024-09-09T16:08:28.1605340Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/std/assertions.nim(36, 13) raiseAssert
2024-09-09T16:08:28.1607975Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(53, 5) sysFatal
2024-09-09T16:08:28.1614180Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(53, 5) Error: unhandled exception: /github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/networking/network_metadata.nim(324, 15) `ConsensusFork.high == ConsensusFork.Electra`  [AssertionDefect]
2024-09-09T16:08:28.2286000Z make: *** [Makefile:447: nimbus_beacon_node] Error 1
```
can replicate locally by running `make nimbus_beacon_node`.

General risk with the adding the `ConsensusFork`: it makes rebasing, etc more difficult. It's a very invasive change and practically, when Nimbus does hardfork updates, I try to separate out sequences of minimal-risk changes, rather than one big feature branch of sorts. This one error is just the beginning -- yes, of course, it's possible to fix, but then there's the next one and the next one and ...

It depends how ePBS should be tested -- my inclination is to probably treat it as a kind of part of the the Electra fork (but declared symbolically, `const EbpsFork = ConsensusFork.Electra` and systematically using that instead, or similar, to avoid confusion of actually-electra and ePBS), and just figure that this branch can't yet be used properly as part of `unstable`. Then if/when it's clear which fork it's part of, switch that `EpbsFork` to the fork in question, after it's already added to `ConsensusFork`. Combining the two will probably get messy.

We're not going to merge a tentative `ConsensusFork` anyway so by including that it means it's not going to be merge able anyway.

2024-09-09 16:15 UTC, tersec commented
Basically I think https://github.com/status-im/nimbus-eth2/pull/6443/commits/ef50df0b4cf9a074207e6b2fb67b32aab56cec8e should be reconsidered

2024-09-09 19:24 UTC, Tomi-3-0 commented
> https://github.com/status-im/nimbus-eth2/actions/runs/10752309189/job/29884832856?pr=6443
> 
> ```
> 2024-09-09T16:08:28.1595661Z stack trace: (most recent call last)
> 2024-09-09T16:08:28.1599116Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/networking/network_metadata.nim(324, 11) network_metadata
> 2024-09-09T16:08:28.1602221Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/std/assertions.nim(41, 14) failedAssertImpl
> 2024-09-09T16:08:28.1605340Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/std/assertions.nim(36, 13) raiseAssert
> 2024-09-09T16:08:28.1607975Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(53, 5) sysFatal
> 2024-09-09T16:08:28.1614180Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(53, 5) Error: unhandled exception: /github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/networking/network_metadata.nim(324, 15) `ConsensusFork.high == ConsensusFork.Electra`  [AssertionDefect]
> 2024-09-09T16:08:28.2286000Z make: *** [Makefile:447: nimbus_beacon_node] Error 1
> ```
> 
> can replicate locally by running `make nimbus_beacon_node`.
> 
> General risk with the adding the `ConsensusFork`: it makes rebasing, etc more difficult. It's a very invasive change and practically, when Nimbus does hardfork updates, I try to separate out sequences of minimal-risk changes, rather than one big feature branch of sorts. This one error is just the beginning -- yes, of course, it's possible to fix, but then there's the next one and the next one and ...
> 
> It depends how ePBS should be tested -- my inclination is to probably treat it as a kind of part of the the Electra fork (but declared symbolically, `const EbpsFork = ConsensusFork.Electra` and systematically using that instead, or similar, to avoid confusion of actually-electra and ePBS), and just figure that this branch can't yet be used properly as part of `unstable`. Then if/when it's clear which fork it's part of, switch that `EpbsFork` to the fork in question, after it's already added to `ConsensusFork`. Combining the two will probably get messy.
> 
> We're not going to merge a tentative `ConsensusFork` anyway so by including that it means it's not going to be merge able anyway.

This makes a lot of sense. Thank you!

2024-09-12 03:14 UTC, tersec commented on beacon_chain/spec/presets/minimal/epbs_preset.nim
> +# https://github.com/ethereum/consensus-specs/blob/1508f51b80df5488a515bfedf486f98435200e02/specs/_features/eipxxxx/beacon-chain.md#preset
https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.5/specs/_features/eip7732/beacon-chain.md#preset

2024-09-12 03:20 UTC, tersec commented on beacon_chain/spec/presets/mainnet/epbs_preset.nim
> +# https://github.com/ethereum/consensus-specs/blob/1508f51b80df5488a515bfedf486f98435200e02/specs/_features/eipxxxx/beacon-chain.md#preset
https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.5/specs/_features/eip7732/beacon-chain.md#preset

2024-09-12 03:21 UTC, tersec commented on beacon_chain/spec/ptc_status.nim
> +# https://github.com/ethereum/consensus-specs/blob/1508f51b80df5488a515bfedf486f98435200e02/specs/_features/eipxxxx/beacon-chain.md#constants
https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.5/specs/_features/eip7732/beacon-chain.md#payload-status

2024-09-12 03:21 UTC, tersec commented on beacon_chain/spec/presets/gnosis/epbs_preset.nim
> +# https://github.com/ethereum/consensus-specs/blob/1508f51b80df5488a515bfedf486f98435200e02/specs/_features/eipxxxx/beacon-chain.md#preset
https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.5/specs/_features/eip7732/beacon-chain.md#preset

2024-09-12 03:22 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +  # Since epbs.BeaconState implies typeof(state).kind >= ConsensusFork.Electra, we can remove the 'when' condition
Can line-break this comment to 80 chars

2024-09-12 03:23 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +      when typeof(body).kind >= ConsensusFork.Electra:
This `when` will always be true. ePBS won't happen before Electra

2024-09-12 03:24 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +  when typeof(body).kind >= ConsensusFork.Capella:
This `when` will always be true. ePBS won't happen before Capella

2024-09-12 03:25 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    cfg: RuntimeConfig, body: SomeForkyBeaconBlockBody,
This can't apply to any random `ForkyBlindedBeaconBlockBody`, because it has to be a body which applies to an `epbs.BeaconState`, which means it must be an ePBS block body. No generics necessary/useful here.

2024-09-12 03:26 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +        when typeof(body).kind >= ConsensusFork.Electra:
This `when` will always be true. ePBS won't happen before Electra

2024-09-12 03:26 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    when typeof(body).kind >= ConsensusFork.Electra:
This `when` will always be true. ePBS won't happen before Electra

2024-09-12 03:29 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    var epochParticipation: EpochParticipationFlags
This whole section can be more safely phrased as
```nim
  let epochParticipation =
    if state.slot mod SLOTS_PER_EPOCH == 0:
      state.previous_epoch_participation
    else:
      state.current_epoch_participation
```
i.e. a https://nim-lang.org/docs/manual.html#statements-and-expressions-if-expression instead of a https://nim-lang.org/docs/manual.html#statements-and-expressions-if-statement

which works with https://status-im.github.io/nim-style-guide/language.vardecl.html

2024-09-12 03:37 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    let proposer_reward_denominator =
This is a constant and can use `const` here to compute it at compile-time rather than runtime

2024-09-12 03:39 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    body: SomeForkyBeaconBlockBody, base_reward_per_increment: Gwei,
Only ePBS blocks can be processed on top of ePBS states, not any `SomeForkyBeaconBlockBody`

2024-09-12 03:44 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +    output = output.union(committee_attesters)
In-place `HashSet` union can be done with https://nim-lang.org/docs/sets.html#incl%2CHashSet%5BA%5D%2CHashSet%5BA%5D directly: `output.incl(committee_attesters)`

2024-09-12 03:47 UTC, tersec commented on beacon_chain/spec/payload_attestations.nim
> +      output[pos] = index
```nim
  var
    output: List[ValidatorIndex, Limit PTC_SIZE]
```
constructs a default 0-item list (it's basically the same thing as a `seq[ValidatorIndex]` for Nim), so there aren't any existing elements to index into. This line is guaranteed to generate an index out of range defect.

2024-09-12 04:05 UTC, tersec commented on beacon_chain/spec/signatures.nim
> +  # Fork-agnostic domain since address changes are valid across forks
Comment not relevant to function; this isn't computing an address change signing root

2024-09-12 04:05 UTC, tersec commented on beacon_chain/spec/signatures.nim
> +  # Fork-agnostic domain since address changes are valid across forks
Comment not relevant to function; this isn't computing an address change signing root

2024-09-12 04:21 UTC, tersec commented on beacon_chain/spec/signatures.nim
> +  doAssert genesisFork.previous_version == genesisFork.current_version
The execution payload headers are not fork-agnostic and this condition won't in general hold. https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.5/specs/_features/eip7732/beacon-chain.md#new-verify_execution_payload_header_signature says:
```python
def verify_execution_payload_header_signature(state: BeaconState, 
                                              signed_header: SignedExecutionPayloadHeader) -> bool:
    # Check the signature
    builder = state.validators[signed_header.message.builder_index]
    signing_root = compute_signing_root(signed_header.message, get_domain(state, DOMAIN_BEACON_BUILDER))
    return bls.Verify(builder.pubkey, signing_root, signed_header.signature)
```
and
https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.5/specs/phase0/beacon-chain.md#get_domain has
```python
def get_domain(state: BeaconState, domain_type: DomainType, epoch: Epoch=None) -> Domain:
    """
    Return the signature domain (fork version concatenated with domain type) of a message.
    """
    epoch = get_current_epoch(state) if epoch is None else epoch
    fork_version = state.fork.previous_version if epoch < state.fork.epoch else state.fork.current_version
    return compute_domain(domain_type, fork_version, state.genesis_validators_root)
```
That is, when it's called from `verify_execution_payload_header_signature` this way, with two arguments, `get_domain` does not use `GENESIS_EPOCH` but rather `get_current_epoch(state)`.

The signatures are a function of fork in this case, and that needs to be reflected in this `compute_execution_payload_header_signing_root` function.

2024-09-12 04:27 UTC, tersec commented on beacon_chain/spec/signatures.nim
> +    genesisFork: Fork, genesis_validators_root: Eth2Digest,
Also not genesis fork.

https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.5/specs/_features/eip7732/beacon-chain.md#new-verify_execution_payload_envelope_signature reads
```python
def verify_execution_payload_envelope_signature(
        state: BeaconState, signed_envelope: SignedExecutionPayloadEnvelope) -> bool:
    builder = state.validators[signed_envelope.message.builder_index]
    signing_root = compute_signing_root(signed_envelope.message, get_domain(state, DOMAIN_BEACON_BUILDER))
    return bls.Verify(builder.pubkey, signing_root, signed_envelope.signature)
```
so it's another two-parameter call to `get_domain(...)`, regarding which see https://github.com/status-im/nimbus-eth2/pull/6443/files#r1756088823

2024-09-12 04:28 UTC, tersec commented on beacon_chain/spec/signatures.nim
> +    genesisFork: Fork, genesis_validators_root: Eth2Digest,
None of these are `genesisFork` (in `get_execution_payload_header_signature`, `verify_execution_payload_header_signature`, `compute_execution_payload_envelope_signing_root`, etc)

2024-09-12 04:29 UTC, tersec commented on beacon_chain/spec/signatures.nim
> +  doAssert genesisFork.previous_version == genesisFork.current_version
Assertion will in general not hold true, because not genesis fork. That's basically what it's testing for; there's by definition no previous fork for the genesis fork

2024-09-12 04:30 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    return
should return some value of type `Result[void, cstring]`, either `ok()` or `err("some string literal")`

2024-09-12 04:31 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +  # Since epbs.BeaconState implies typeof(state).kind >= ConsensusFork.Electra, we can remove the 'when' condition
This comment refers to what is now some ghost `when` condition which doesn't exist anymore. No need for this comment

2024-09-12 04:36 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +      assert envelope.state_root == hash_tree_root(state)
Should use https://nim-lang.org/docs/assertions.html#doAssert.t%2Cuntyped%2Cstring rather than https://nim-lang.org/docs/assertions.html#assert.t%2Cuntyped%2Cstring because the former:
> is always turned on regardless of `--assertions`.

2024-09-12 04:38 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +      let pubkey = state.validators.mitem(vidx).pubkey()
Why `mitem`? It shouldn't have to modify. `item` should suffice and avoids invalidating the `hash_tree_root` cache of the validator

2024-09-12 04:39 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    let pubkey = state.validators.mitem(vidx).pubkey()
Should be able to use `item()` rather than (expensive due to htr cache invalidation) `mitem`

2024-09-13 18:14 UTC, Tomi-3-0 commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    var epochParticipation: EpochParticipationFlags
I think `var epochParticipation` should still be used since it needs to be passed as a mutable structure, changing just the `let`  to `var` like so:
```
    var epochParticipation =
      if state.slot mod SLOTS_PER_EPOCH == 0:
        state.previous_epoch_participation
      else:
        state.current_epoch_participation
```

2024-09-13 21:49 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    var epochParticipation: EpochParticipationFlags
Sure, still an improvement

2024-09-13 21:52 UTC, tersec commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    var epochParticipation: EpochParticipationFlags
One issue though is that if the resulting `epochParticipation` local variable is modified, the underlying state is not. So it won't accomplish that goal.

2024-09-26 19:12 UTC, Redidacove requested changes

2024-09-26 19:12 UTC, Redidacove commented on beacon_chain/spec/state_transition_block_epbs.nim
> +    return err("parent block is empty")
We don't error if parent block is full, we just return nil and error nil in prysm

2024-09-26 19:51 UTC, Redidacove requested changes

2024-09-26 19:51 UTC, Redidacove commented on beacon_chain/spec/payload_attestations.nim
> +    state, slot, payload_attestation, cache)
shouldn't we sort attesting indices here before putting it into IndexedPayloadAttestation

2024-10-06 19:36 UTC, Redidacove requested changes

2024-10-06 19:36 UTC, Redidacove commented on beacon_chain/spec/payload_attestations.nim
> +  for slot in start_slot .. start_slot + SLOTS_PER_EPOCH - 1:
```suggestion
  for slot in start_slot .. <end_slot:
``` 
Isn't it better to take a variable like end_slot = start_slot + SLOTS_PER_EPOCH:
that would  be more readable ib.

2024-10-07 21:06 UTC, Redidacove requested changes

2024-10-07 21:06 UTC, Redidacove commented on beacon_chain/spec/datatypes/epbs.nim
> +    # [New in PBS]
```suggestion
    # [New in EIP-7732]
```

2024-10-08 03:31 UTC, tersec commented
```
2024-10-08T03:19:48.2521970Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/spec/datatypes/electra.nim(306, 3) Error: redefinition of 'ExecutionRequests'; previous declaration here: /github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/spec/datatypes/electra.nim(193, 3)
```

2024-10-08 10:00 UTC, Redidacove commented
> ```
> 2024-10-08T03:19:48.2521970Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/spec/datatypes/electra.nim(306, 3) Error: redefinition of 'ExecutionRequests'; previous declaration here: /github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/spec/datatypes/electra.nim(193, 3)
> ```
Removing it 👍

2024-10-08 12:55 UTC, tersec commented
```
2024-10-08T12:12:55.6224986Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/spec/datatypes/epbs.nim(37, 23) Error: undeclared identifier: 'PendingBalanceDeposit'
2024-10-08T12:12:55.6458434Z make: *** [Makefile:447: wss_sim] Error 1
--
2024-10-08T12:12:56.6417447Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/spec/datatypes/epbs.nim(37, 23) Error: undeclared identifier: 'PendingBalanceDeposit'
2024-10-08T12:12:56.6684431Z make: *** [Makefile:447: ncli_db] Error 1
--
2024-10-08T12:12:57.2701357Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/spec/datatypes/epbs.nim(37, 23) Error: undeclared identifier: 'PendingBalanceDeposit'
2024-10-08T12:12:57.2781920Z make: *** [Makefile:447: deposit_contract] Error 1
2024-10-08T12:12:57.3029205Z make: *** [Makefile:447: ncli] Error 1
--
2024-10-08T12:12:58.3929001Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/spec/datatypes/epbs.nim(37, 23) Error: undeclared identifier: 'PendingBalanceDeposit'
2024-10-08T12:12:58.4317242Z make: *** [Makefile:447: nimbus_validator_client] Error 1
2024-10-08T12:12:58.6439010Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/spec/datatypes/epbs.nim(37, 23) Error: undeclared identifier: 'PendingBalanceDeposit'
2024-10-08T12:12:58.6893775Z make: *** [Makefile:447: mev_mock] Error 1
--
2024-10-08T12:13:03.5207018Z /github-runner/workspace/nimbus-eth2/nimbus-eth2/beacon_chain/spec/datatypes/epbs.nim(37, 23) Error: undeclared identifier: 'PendingBalanceDeposit'
2024-10-08T12:13:03.5736294Z make: *** [Makefile:447: nimbus_light_client] Error 1
```
https://github.com/ethereum/consensus-specs/releases/tag/v1.5.0-alpha.7 contains https://github.com/ethereum/consensus-specs/pull/3818 which replaces `PendingBalanceDeposit` with `PendingDeposit`

2024-10-09 00:33 UTC, tersec commented
Haven't checked in detail yet, but something went awry with that merge. Some conflicts that I don't think were there before:
![2024-10-09T00:31:48,158859098+00:00](https://github.com/user-attachments/assets/31066590-d168-42e1-a25f-cf65965d83fd)

2024-10-09 03:24 UTC, Redidacove commented
Strange there are conflicts in vendor packages.

2024-10-09 04:23 UTC, tersec commented
> Strange there are conflicts in vendor packages.

They aren't conflicts in the vendor packages as such, but different versions of the packages specified somehow in the git repository history so that the merge process can't automatically complete.

Specifically, the PRs:
- https://github.com/status-im/nimbus-eth2/pull/6610 accounts for the changes in `nim-eth` and `nim-stew`; and
- https://github.com/status-im/nimbus-eth2/pull/6611 accounts for the change in `nim-unittest2`

2024-10-09 19:45 UTC, Tomi-3-0 commented on beacon_chain/spec/payload_attestations.nim
> +  for slot in start_slot .. start_slot + SLOTS_PER_EPOCH - 1:
Does this give any performance advantage? I don't think so

2024-10-14 17:12 UTC, tersec commented
The files:
- the binary executable `tests/consensus_spec/bellatrix/test_fixture_operations` (the one without the `.nim` extension);
- the binary executable `tests/consensus_spec/electra/test_fixture_operations` (ditto, the one without the `.nim` extension)
- the binary executable `beacon_chain/spec/helpers` (also, the one without the `.nim` extension); and
- `ubmodule update --init --recursive` (as in, there's a file literally named `ubmodule update --init --recursive` in this branch)

should not be part of the git repository.

2024-10-14 17:13 UTC, tersec commented on .vscode/tasks.json
Why was this file deleted?

2024-10-14 17:52 UTC, tersec commented
Current build failure (locally reproducible via `make all_tests`):
```
/github-runner/workspace/nimbus-eth2/nimbus-eth2/tests/test_helpers.nim(276, 33) Error: type mismatch
Expression: remove_flag(flag, flag_index)
  [1] flag: uint8
  [2] flag_index: int

Expected one of (first mismatch at [position]):
[2] func remove_flag(flags: ParticipationFlags; flag_index: TimelyFlag): ParticipationFlags
```

2024-10-14 18:33 UTC, Tomi-3-0 commented on .vscode/tasks.json
> Why was this file deleted?

I used github codespaces, might have been deleted in Codespaces due to automatic environment configuration.

2024-10-14 18:47 UTC, Tomi-3-0 commented
> Current build failure (locally reproducible via `make all_tests`):
> 
> ```
> /github-runner/workspace/nimbus-eth2/nimbus-eth2/tests/test_helpers.nim(276, 33) Error: type mismatch
> Expression: remove_flag(flag, flag_index)
>   [1] flag: uint8
>   [2] flag_index: int
> 
> Expected one of (first mismatch at [position]):
> [2] func remove_flag(flags: ParticipationFlags; flag_index: TimelyFlag): ParticipationFlags
> ```



> ):

>_<

2024-10-14 18:47 UTC, Tomi-3-0 commented
> > Current build failure (locally reproducible via `make all_tests`):
> > ```
> > /github-runner/workspace/nimbus-eth2/nimbus-eth2/tests/test_helpers.nim(276, 33) Error: type mismatch
> > Expression: remove_flag(flag, flag_index)
> >   [1] flag: uint8
> >   [2] flag_index: int
> > 
> > Expected one of (first mismatch at [position]):
> > [2] func remove_flag(flags: ParticipationFlags; flag_index: TimelyFlag): ParticipationFlags
> > ```
> 
> > _<

2024-10-14 18:48 UTC, Tomi-3-0 commented
> Current build failure (locally reproducible via `make all_tests`):
> 
> ```
> /github-runner/workspace/nimbus-eth2/nimbus-eth2/tests/test_helpers.nim(276, 33) Error: type mismatch
> Expression: remove_flag(flag, flag_index)
>   [1] flag: uint8
>   [2] flag_index: int
> 
> Expected one of (first mismatch at [position]):
> [2] func remove_flag(flags: ParticipationFlags; flag_index: TimelyFlag): ParticipationFlags
> ```

:'(

2024-10-16 09:25 UTC, tersec commented
```
/github-runner/workspace/nimbus-eth2/nimbus-eth2/vendor/nim-unittest2/unittest2.nim: In function ‘_ZN23test_message_signatures20runTestX60gensym450_E6string6string’:
/github-runner/workspace/nimbus-eth2/nimbus-eth2/vendor/nim-unittest2/unittest2.nim:1101:15: error: stack usage might be 5658432 bytes [-Werror=stack-usage=]
 1101 |   proc runTest(suiteName, testName: string): TestStatus {.raises: [], gensym.} =
      |               ^
/github-runner/workspace/nimbus-eth2/nimbus-eth2/vendor/nim-unittest2/unittest2.nim: In function ‘_ZN23test_message_signatures20runTestX60gensym509_E6string6string’:
/github-runner/workspace/nimbus-eth2/nimbus-eth2/vendor/nim-unittest2/unittest2.nim:1101:15: error: stack usage might be 5658944 bytes [-Werror=stack-usage=]
/github-runner/workspace/nimbus-eth2/nimbus-eth2/vendor/nim-unittest2/unittest2.nim: In function ‘_ZN23test_message_signatures20runTestX60gensym568_E6string6string’:
/github-runner/workspace/nimbus-eth2/nimbus-eth2/vendor/nim-unittest2/unittest2.nim:1101:15: error: stack usage might be 5658352 bytes [-Werror=stack-usage=]
lto1: some warnings being treated as errors
make[2]: *** [/tmp/cckbluCt.mk:263: /tmp/ccXwZhhR.ltrans87.ltrans.o] Error 1
make[2]: *** Waiting for unfinished jobs....
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[1]: *** [nimcache/release/all_tests/all_tests.makefile:3752: build] Error 1
```
The CI checks that maximum per-function static stack usage is 1MB:
https://github.com/status-im/nimbus-eth2/blob/ec0accf29033bbb2fe718c130694c46e54c26387/.github/workflows/ci.yml#L129-L138

2024-11-28 10:42 UTC, closed without merging